### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by unickhow** [unickhow/jirassic#1]
- [x] token link should be external `target="_blank"`
- [x] markdown preview in [marked](https://github.com/markedjs/marked)
- [x] store `Owner` field in lf
- [x] copy button interaction
- [x] swap button for base and compare
- [x] empty status
- [x] dna loading
- [x] align theme colors
- [ ] test
- [x] token expired notification 
- [x] multiple workspace
- [ ] case sensitive
- [ ] update v2 icon in flatten style
- [ ] *renew UI?*
- [x] add contributor
- [ ] custom inline template, e.g., `- {{ticket}} | {{title}} -- {{contributor}}`

🐛**Bug**

- [x] Title overflow should be truncated or do something => remove Button type
- [x] Duplicate insert issue => new Set
- [x] clear content on generate
- [x] workspace name existence checking
- [x] trim owner name
